<a href="https://colab.research.google.com/github/ducthpoc/DataAnlalysis-AustinDavis/blob/main/DataAnalyticsEp3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importing libraries we're going to use
import pandas as pd
from google.colab import files
import io

# Upload file and turn it into a DataFrame
dataFile = files.upload()
dataset = pd.read_csv(io.BytesIO(dataFile['AI_index_db.csv']))

Saving AI_index_db.csv to AI_index_db.csv

In [ ]:
# View first dataset entries
dataset.head()

,Country,Talent,Infrastructure,Operating Environment,Research,Development,Government Strategy,Commercial,Total score,Region,Cluster,Income group,Political regime
0,United States of America,100.00,94.02,64.56,100.00,100.00,77.39,100.00,100.00,Americas,Power players,High,Liberal democracy
1,China,16.51,100.00,91.57,71.42,79.97,94.87,44.02,62.92,Asia-Pacific,Power players,Upper middle,Closed autocracy
2,United Kingdom,39.65,71.43,74.65,36.50,25.03,82.82,18.91,40.93,Europe,Traditional champions,High,Liberal democracy
3,Canada,31.28,77.05,93.94,30.67,25.78,100.00,14.88,40.19,Americas,Traditional champions,High,Liberal democracy
4,Israel,35.76,67.58,82.44,32.63,27.96,43.91,27.33,39.89,Middle East,Rising stars,High,Liberal democracy

In [ ]:
# Describe function
dataset.describe()

,Talent,Infrastructure,Operating Environment,Research,Development,Government Strategy,Commercial,Total score
count,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000
mean,16.803065,63.503710,66.925484,16.610000,14.824677,57.865645,6.171935,23.914677
std,15.214963,20.217525,20.000424,17.413996,19.419279,26.252448,14.029632,15.123586
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7.365000,55.857500,58.107500,3.032500,1.202500,41.030000,0.697500,14.805000
50%,13.445000,65.230000,69.505000,12.930000,9.005000,63.930000,2.585000,23.220000
75%,24.567500,75.947500,80.500000,25.412500,19.980000,77.952500,5.307500,30.487500
max,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000

In [ ]:
# Singular column selection
dataset["Research"]

0     100.00
1      71.42
2      36.50
3      30.67
4      32.63
       ...
57      0.12
58      2.08
59      0.07
60      0.45
61      2.17
Name: Research, Length: 62, dtype: float64

In [ ]:
# Multiple column selection
talentDataframe = dataset[["Country", "Talent"]]
talentDataframe

                     Country  Talent
0   United States of America  100.00
1                      China   16.51
2             United Kingdom   39.65
3                     Canada   31.28
4                     Israel   35.76
..                       ...     ...
57                 Sri Lanka    6.27
58                     Egypt    1.11
59                     Kenya    0.75
60                   Nigeria    2.74
61                  Pakistan    8.00

[62 rows x 2 columns]

In [ ]:
# loc - Location
# iloc - Integer Location

In [ ]:
# Selecting specific cell/row
dataset.loc[0]

Country                  United States of America
Talent                                      100.0
Infrastructure                              94.02
Operating Environment                       64.56
Research                                    100.0
Development                                 100.0
Government Strategy                         77.39
Commercial                                  100.0
Total score                                 100.0
Region                                   Americas
Cluster                             Power players
Income group                                 High
Political regime                Liberal democracy
Name: 0, dtype: object

In [ ]:
# Selecting multiple rows/columns
dataset.loc[:, "Research":]

,Research,Development,Government Strategy,Commercial,Total score,Region,Cluster,Income group,Political regime
0,100.00,100.00,77.39,100.00,100.00,Americas,Power players,High,Liberal democracy
1,71.42,79.97,94.87,44.02,62.92,Asia-Pacific,Power players,Upper middle,Closed autocracy
2,36.50,25.03,82.82,18.91,40.93,Europe,Traditional champions,High,Liberal democracy
3,30.67,25.78,100.00,14.88,40.19,Americas,Traditional champions,High,Liberal democracy
4,32.63,27.96,43.91,27.33,39.89,Middle East,Rising stars,High,Liberal democracy
...,...,...,...,...,...,...,...,...,...
57,0.12,0.95,35.57,0.09,6.62,Asia-Pacific,Nascent,Lower middle,Electoral democracy
58,2.08,1.54,68.72,0.31,4.83,Middle East,Nascent,Lower middle,Electoral autocracy
59,0.07,12.15,7.75,0.31,2.30,Africa,Nascent,Lower middle,Electoral autocracy
60,0.45,2.06,7.75,0.33,1.38,Africa,Nascent,Lower middle,Electoral autocracy
61,2.17,1.09,13.92,0.27,0.00,Asia-Pacific,Nascent,Lower middle,Electoral autocracy

In [ ]:
# Selecting rows/columns based on a condition (Filtering)
dataset.loc[dataset["Region"].isin(["Europe", "Americas", "Middle East"])]

,Country,Talent,Infrastructure,Operating Environment,Research,Development,Government Strategy,Commercial,Total score,Region,Cluster,Income group,Political regime
0,United States of America,100.00,94.02,64.56,100.00,100.00,77.39,100.00,100.00,Americas,Power players,High,Liberal democracy
2,United Kingdom,39.65,71.43,74.65,36.50,25.03,82.82,18.91,40.93,Europe,Traditional champions,High,Liberal democracy
3,Canada,31.28,77.05,93.94,30.67,25.78,100.00,14.88,40.19,Americas,Traditional champions,High,Liberal democracy
4,Israel,35.76,67.58,82.44,32.63,27.96,43.91,27.33,39.89,Middle East,Rising stars,High,Liberal democracy
7,The Netherlands,33.83,81.99,88.05,25.54,30.17,62.35,4.97,36.35,Europe,Rising stars,High,Liberal democracy
8,Germany,27.63,77.22,70.22,35.84,24.79,84.65,8.29,36.04,Europe,Traditional champions,High,Liberal democracy
9,France,28.32,77.15,80.02,25.48,21.44,91.20,7.65,34.42,Europe,Traditional champions,High,Liberal democracy
11,Ireland,29.93,89.50,70.15,16.79,30.85,69.44,3.94,33.04,Europe,Rising stars,High,Liberal democracy
12,Finland,24.99,71.60,78.76,25.21,18.32,85.99,4.64,31.36,Europe,Rising stars,High,Liberal democracy
13,Denmark,27.07,74.08,85.39,26.01,8.92,74.23,3.46,30.87,Europe,Rising stars,High,Liberal democracy
14,Luxembourg,21.66,94.88,66.96,19.39,19.95,66.69,4.68,30.73,Europe,Waking up,High,Liberal democracy
17,Switzerland,25.63,78.43,44.14,38.24,23.11,12.18,7.76,30.25,Europe,Rising stars,High,Liberal democracy
18,Sweden,28.21,75.19,66.77,27.61,17.81,40.35,4.51,29.85,Europe,Waking up,High,Liberal democracy
20,Spain,17.61,73.32,75.36,18.60,10.87,91.28,3.08,26.95,Europe,Rising stars,High,Liberal democracy
21,Austria,16.97,64.49,76.30,23.56,17.81,72.14,3.08,26.89,Europe,Waking up,High,Electoral democracy
22,Estonia,18.74,63.65,88.67,11.75,9.31,72.08,12.51,26.60,Europe,Waking up,High,Liberal democracy
24,Norway,27.61,76.20,36.65,21.18,13.56,59.05,3.95,25.77,Europe,Waking up,High,Liberal democracy
25,Saudi Arabia,4.49,70.80,100.00,13.63,14.38,91.63,4.73,25.60,Middle East,Waking up,High,Closed autocracy
26,Belgium,15.17,65.10,64.08,22.15,19.81,63.58,5.31,25.52,Europe,Waking up,High,Liberal democracy
27,Poland,14.21,70.96,99.56,10.60,9.09,78.14,2.25,25.20,Europe,Waking up,High,Electoral democracy
28,Slovenia,13.02,72.06,94.55,19.10,1.06,80.38,0.61,25.19,Europe,Waking up,High,Electoral democracy
30,Italy,11.09,64.76,83.25,20.30,14.66,61.43,2.64,24.45,Europe,Waking up,High,Liberal democracy
31,Russia,12.46,62.59,52.85,14.21,19.48,90.40,1.38,21.99,Europe,Waking up,Upper middle,Electoral autocracy
32,Malta,15.87,67.12,70.96,5.96,11.72,70.49,4.30,21.85,Europe,Waking up,High,Electoral democracy
33,United Arab Emirates,2.65,79.16,72.12,5.13,15.53,81.38,3.22,21.17,Middle East,Waking up,High,Closed autocracy
34,Portugal,13.43,64.20,80.66,8.96,3.92,70.69,2.05,20.89,Europe,Waking up,High,Electoral democracy
35,Czech Republic,11.11,64.26,76.97,11.26,2.70,70.29,1.75,20.31,Europe,Waking up,High,Electoral democracy
36,Iceland,18.45,72.45,41.19,18.29,0.19,22.15,5.74,19.81,Europe,Waking up,High,Liberal democracy
37,Lithuania,14.30,63.19,80.67,3.22,6.18,64.28,1.77,19.59,Europe,Waking up,High,Electoral democracy
38,Brazil,13.46,62.61,72.82,4.83,5.07,67.72,1.36,18.89,Americas,Waking up,Upper middle,Electoral democracy
39,Greece,7.62,55.44,83.58,15.12,2.21,22.15,0.92,17.33,Europe,Waking up,High,Liberal democracy
40,Slovakia,8.55,65.36,88.71,2.97,0.34,43.07,0.67,17.24,Europe,Waking up,High,Electoral democracy
41,Hungary,10.34,69.17,58.01,4.31,5.40,55.01,1.08,17.00,Europe,Waking up,High,Electoral autocracy
43,Mexico,1.72,41.85,97.03,8.11,4.46,54.21,0.78,15.48,Americas,Waking up,Upper middle,Electoral democracy
44,Chile,10.56,61.97,56.73,1.49,0.67,60.50,2.95,15.33,Americas,Waking up,High,Liberal democracy
45,Argentina,8.40,56.15,75.95,1.25,3.19,54.94,0.34,15.24,Americas,Waking up,Upper middle,Electoral democracy
46,Qatar,0.00,67.97,62.58,11.94,0.00,33.49,0.00,14.66,Middle East,Waking up,High,Closed autocracy
47,Turkey,8.49,40.74,64.34,9.53,1.02,67.45,0.95,14.39,Europe,Waking up,High,Electoral democracy
48,Colombia,4.97,54.80,62.37,0.00,0.89,85.29,0.50,13.85,Americas,Waking up,Upper middle,Electoral democracy
49,Uruguay,7.28,58.77,70.75,0.73,0.26,30.92,0.43,13.27,Americas,Waking up,High,Liberal democracy
50,Bahrain,4.99,60.39,60.90,2.53,0.00,17.72,0.24,11.79,Middle East,Waking up,High,Closed autocracy
56,Armenia,6.69,37.84,58.40,0.28,0.33,14.40,1.37,8.49,Europe,Waking up,Upper middle,Electoral democracy
58,Egypt,1.11,38.84,0.00,2.08,1.54,68.72,0.31,4.83,Middle East,Nascent,Lower middle,Electoral autocracy

In [ ]:
# Selecting rows/columns based on MULTIPLE conditions
dataset.loc[(dataset["Region"].isin(["Europe", "Americas", "Middle East"])) & (dataset["Operating Environment"] < 70)]

,Country,Talent,Infrastructure,Operating Environment,Research,Development,Government Strategy,Commercial,Total score,Region,Cluster,Income group,Political regime
0,United States of America,100.00,94.02,64.56,100.00,100.00,77.39,100.00,100.00,Americas,Power players,High,Liberal democracy
14,Luxembourg,21.66,94.88,66.96,19.39,19.95,66.69,4.68,30.73,Europe,Waking up,High,Liberal democracy
17,Switzerland,25.63,78.43,44.14,38.24,23.11,12.18,7.76,30.25,Europe,Rising stars,High,Liberal democracy
18,Sweden,28.21,75.19,66.77,27.61,17.81,40.35,4.51,29.85,Europe,Waking up,High,Liberal democracy
24,Norway,27.61,76.20,36.65,21.18,13.56,59.05,3.95,25.77,Europe,Waking up,High,Liberal democracy
26,Belgium,15.17,65.10,64.08,22.15,19.81,63.58,5.31,25.52,Europe,Waking up,High,Liberal democracy
31,Russia,12.46,62.59,52.85,14.21,19.48,90.40,1.38,21.99,Europe,Waking up,Upper middle,Electoral autocracy
36,Iceland,18.45,72.45,41.19,18.29,0.19,22.15,5.74,19.81,Europe,Waking up,High,Liberal democracy
41,Hungary,10.34,69.17,58.01,4.31,5.40,55.01,1.08,17.00,Europe,Waking up,High,Electoral autocracy
44,Chile,10.56,61.97,56.73,1.49,0.67,60.50,2.95,15.33,Americas,Waking up,High,Liberal democracy
46,Qatar,0.00,67.97,62.58,11.94,0.00,33.49,0.00,14.66,Middle East,Waking up,High,Closed autocracy
47,Turkey,8.49,40.74,64.34,9.53,1.02,67.45,0.95,14.39,Europe,Waking up,High,Electoral democracy
48,Colombia,4.97,54.80,62.37,0.00,0.89,85.29,0.50,13.85,Americas,Waking up,Upper middle,Electoral democracy
50,Bahrain,4.99,60.39,60.90,2.53,0.00,17.72,0.24,11.79,Middle East,Waking up,High,Closed autocracy
56,Armenia,6.69,37.84,58.40,0.28,0.33,14.40,1.37,8.49,Europe,Waking up,Upper middle,Electoral democracy
58,Egypt,1.11,38.84,0.00,2.08,1.54,68.72,0.31,4.83,Middle East,Nascent,Lower middle,Electoral autocracy

In [ ]:
# Multiple Filtering Example 2
dataset.loc[(dataset["Infrastructure"] > 50) & (dataset["Region"] == "Asia-Pacific")]

,Country,Talent,Infrastructure,Operating Environment,Research,Development,Government Strategy,Commercial,Total score,Region,Cluster,Income group,Political regime
1,China,16.51,100.00,91.57,71.42,79.97,94.87,44.02,62.92,Asia-Pacific,Power players,Upper middle,Closed autocracy
5,Singapore,39.38,84.30,43.15,37.67,22.55,79.82,15.07,38.67,Asia-Pacific,Rising stars,High,Electoral democracy
6,South Korea,14.54,85.23,68.86,26.66,77.25,87.50,5.41,38.60,Asia-Pacific,Rising stars,High,Liberal democracy
10,Australia,25.43,63.43,61.23,32.63,41.15,82.11,6.72,33.86,Asia-Pacific,Rising stars,High,Liberal democracy
15,Japan,15.18,84.58,57.53,22.51,34.47,71.96,7.31,30.53,Asia-Pacific,Rising stars,High,Liberal democracy
19,Hong Kong,17.56,96.11,59.50,31.51,8.63,33.29,5.30,29.11,Asia-Pacific,Waking up,High,Electoral democracy
23,Taiwan,12.34,77.86,56.67,25.71,19.99,55.97,2.53,25.79,Asia-Pacific,Waking up,High,Liberal democracy
29,New Zealand,23.30,69.78,90.35,12.23,5.96,47.62,2.49,24.88,Asia-Pacific,Waking up,High,Liberal democracy
42,Malaysia,10.44,62.04,73.24,5.57,0.88,47.60,0.63,16.66,Asia-Pacific,Waking up,Upper middle,Electoral autocracy
51,Vietnam,6.34,55.76,37.61,2.03,0.30,68.86,0.31,11.62,Asia-Pacific,Waking up,Lower middle,Closed autocracy

In [ ]:
dataset.head(5)

,Country,Talent,Infrastructure,Operating Environment,Research,Development,Government Strategy,Commercial,Total score,Region,Cluster,Income group,Political regime
0,United States of America,100.00,94.02,64.56,100.00,100.00,77.39,100.00,100.00,Americas,Power players,High,Liberal democracy
1,China,16.51,100.00,91.57,71.42,79.97,94.87,44.02,62.92,Asia-Pacific,Power players,Upper middle,Closed autocracy
2,United Kingdom,39.65,71.43,74.65,36.50,25.03,82.82,18.91,40.93,Europe,Traditional champions,High,Liberal democracy
3,Canada,31.28,77.05,93.94,30.67,25.78,100.00,14.88,40.19,Americas,Traditional champions,High,Liberal democracy
4,Israel,35.76,67.58,82.44,32.63,27.96,43.91,27.33,39.89,Middle East,Rising stars,High,Liberal democracy

In [ ]:
dataset.iloc[0:4, 5:7]

   Development  Government Strategy
0       100.00                77.39
1        79.97                94.87
2        25.03                82.82
3        25.78               100.00

In [ ]:
dataset.iloc[:10, 9:]

         Region                Cluster  Income group     Political regime
0      Americas          Power players          High    Liberal democracy
1  Asia-Pacific          Power players  Upper middle     Closed autocracy
2        Europe  Traditional champions          High    Liberal democracy
3      Americas  Traditional champions          High    Liberal democracy
4   Middle East           Rising stars          High    Liberal democracy
5  Asia-Pacific           Rising stars          High  Electoral democracy
6  Asia-Pacific           Rising stars          High    Liberal democracy
7        Europe           Rising stars          High    Liberal democracy
8        Europe  Traditional champions          High    Liberal democracy
9        Europe  Traditional champions          High    Liberal democracy